### ISSUE TITLE
csv data

### ISSUE THREAD

**Issue by psteinb** [tdd11235813/gearshifft#4]
the csv files produced have an _interesting_ structure. I suggest to dump every measurement (not accumulated statistics into the csv) and leave the statistics and analysis to external programs.

I could for example imagine to convert this:
```
"CuFFT","Outplace_Complex_3D","AllocBuffer",2048,"MiB","AllocPlan",1024,"MiB",512,512,512
        "Label",       "Min",       "Avg",       "Max",       "Std","Counts","Unit"
"Device Runtime",     930.695,     930.936,     931.071,    0.144654,     5,   ms
    "CPU Alloc",     2.11583,     2.12205,     2.12992,  0.00620186,     5,   ms
"Device Upload",      315.57,      315.69,     315.879,    0.116578,     5,   ms
   "Device FFT",     103.921,      103.97,     104.002,   0.0326209,     5,   ms
  "Device iFFT",     103.909,     103.977,     104.029,   0.0451246,     5,   ms
"Device Download",     407.105,     407.225,     407.338,    0.109541,     5,   ms
  "CPU Cleanup",     1.20434,     1.21034,     1.21485,  0.00388729,     5,   ms
  "CPU Runtime",     936.427,     936.662,     936.786,    0.139796,     5,   ms
```
into (I am not sure what `"AllocBuffer",2048,"MiB","AllocPlan",1024,"MiB"` is?)
```
lib, type, comment, memory_mb,shape,id, time, unit
"device runtime",cufft,  Outplace_Complex_3D, ??, 2048, 512x512x512, 0, 930.936, ms
"device runtime",cufft,  Outplace_Complex_3D, ??, 2048, 512x512x512, 1, 931.040, ms
"device runtime",cufft,  Outplace_Complex_3D, ??, 2048, 512x512x512, 2, 930.777, ms
```
This way, all necessary information is preserved with a little bit of redundancy. I'll try to find the source code that produces this and come up with a PR

**Comment by tdd11235813** [comment]
yep, I am going to work on this, so the user can choose between verbose output or real csv output (and not the mixed one as it is at the moment).

AllocBuffer - device buffer size for FFT input/output buffer.
AllocPlan - maximal device buffer size for temporary buffer used by FFT library
( maximum of both forward and backward transformation plan )

**Comment by psteinb** [comment]
ok, great! thanks for the explanation
